const ERROR_MESSAGES = Object.freeze({
	DUPLICATE_USER: 'DUPLICATE_USER',
	DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
	NOT_FOUND_USER: "NOT_FOUND_USER",
	WRONG_LOGIN: 'WRONG_LOGIN',
	WRONG_VERIFICATION_CODE: 'WRONG_VERIFICATION_CODE',
})

export default ERROR_MESSAGES
